name = "eink-bmp-converter"
type = "javascript"
workers_dev = true
compatibility_date = "2022-01-04"

account_id = "a8dcb10a2319e0d66f6dc8ed96056001"
zone_id = "bd77b1710d8a024caced0f0b0377f401"
routes = ["eink-bmp-worker.5gp.de/*"]

[vars]
WORKERS_RS_VERSION = "0.0.7"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir    = "build/worker"
format = "modules"
main   = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type  = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
